plugins {
	id("eclipse")
}

group = "sawfowl.localeapi"
version = "${major}.${minor}.${patch}-${suffix}-S${api}"

subprojects {
	apply {
		plugin 'java'
		plugin 'eclipse'
	}
	java.toolchain.languageVersion = JavaLanguageVersion.of(21)

	repositories {
		mavenCentral()
		maven {
			name = "Sponge"
			url = "https://repo.spongepowered.org/repository/maven-public"
		}
		maven {
			name = "GeyserMC"
			url = "https://repo.opencollab.dev/main/"
		}
	}
	tasks.withType(JavaCompile) {
		options.encoding = 'UTF-8'
		it.options.getRelease().set(21)
	}
	configurations {
		doc {
			transitive = false
		}
	}
}

subprojects.each { subproject -> evaluationDependsOn(subproject.path)}
